#+title: LS4GAN Containers
#+EXPORT_FILE_NAME: index.html
#+setupfile: https://ls4gan.github.io/other/setup-page.org
#+options: toc:t

Source files to build containers used for LS4GAN

* General instruction

We make Docker containers which can then be used in this form or
derived into Singularity containers.

** Usage

The containers are provided as ~Dockerfile~ with some supporting
files.  They may be built and run locally or used via docker-hub or
similar.

** Build

Generally:

#+begin_example
  $ cd docker/<name>
  $ docker build -t ls4gan/<name> .
#+end_example

** Run

Each container has its own entry target, but typically this is
~/bin/bash/~ and so one may interactively run a container like

#+begin_example
  docker run -ti ls4gan/<name>
#+end_example

** Singularity

Derive a Singularity container from local docker

#+begin_example
❯ singularity build ls4gan-<name>.img docker-daemon://ls4gan/<name>:latest
#+end_example


* Containers

** wirecell

Provides Wire-Cell Toolkit C++ and Python and their externals.  It is
built on a minimal Debian with WCT and additional software installed
under ~/usr/local/~

This environment can be used to run any "stand-alone" ~wire-cell~ job
or any of the ~wirecell-*~ Python CLIs.  It also provides lots of
Python goodies including Numpy, Matplotlib, ipython, JupyterLab
(needing special ~docker run~ to see its ports).

** TODO runner

This container provides (will provide) support for running a toyzero
pipeline as a single job.  It rides on top of the wirecell container.

** TODO notebook

This container provides (will provide) support for JupyterLab
notebooks.

* Registry

The images may be available in a docker registry near you.

** Docker Hub

The images are uploaded to Docker Hub and can be retrieved with, eg:

#+begin_example
  $ docker pull ls4gan/wirecell
#+end_example

Available images are listed at https://hub.docker.com/u/ls4gan

** BNL/SDCC

The containers are registered to ~registry.sdcc.bnl.gov~ which
internal to BNL.  On a host which can access this server you use the
registry like you would dockerhub.  Eg:

#+begin_example
❯ docker pull registry.sdcc.bnl.gov/toyzero/wirecell
#+end_example

Outside the BNL network it is possible to access the registry by
forwarding a local port via SSH to an internal HTTPS proxy.  

Basically [[https://docs.docker.com/config/daemon/systemd/#httphttps-proxy][docker guidance on setting HTTP/HTTPS proxy]].

For example

#+begin_example
# cat <<EOF > /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:3128"
Environment="HTTPS_PROXY=http://127.0.0.1:3128"
Environment="NO_PROXY=localhost,127.0.0.1,.home,haiku"
EOF
# systemctl daemon-reload
# systemctl restart docker
#+end_example

It is also helpful to add the internal IP address to ~/etc/hosts~.

It should now be possible to login

#+begin_example
❯ docker login registry.sdcc.bnl.gov
#+end_example

And the two steps to register and upload an image:

#+begin_example
❯ docker tag ls4gan/wirecell registry.sdcc.bnl.gov/toyzero/wirecell
❯ docker push registry.sdcc.bnl.gov/toyzero/wirecell
#+end_example

Or, ~docker pull~ as above.

** Singularity

A Singularity image can be useful for running on batch systems.

*** Docker Hub


#+begin_example
❯ singularity build ls4gan-wirecell.sif docker://ls4gan/wirecell
❯ singularity exec ls4gan-wirecell.sif bash -c "/usr/local/bin/wire-cell --help"
#+end_example


*** SDCC Registry

Currently does not work


#+begin_example
❯ singularity pull --docker-login docker://registry.sdcc.bnl.gov/ls4gan/toyzero/wirecell
Enter Docker Username: bvlbne
Enter Docker Password: 
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://registry.sdcc.bnl.gov/ls4gan/toyzero/wirecell: error pinging docker registry registry.sdcc.bnl.gov: Get "https://registry.sdcc.bnl.gov/v2/": dial tcp 130.199.148.226:443: i/o timeout
#+end_example

